#nullable enable
using System.Collections.Generic;
using Content.Shared.GameObjects.Components.Body.Part;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.GameObjects.Components.Body.Surgery
{
    [GenerateTypedNameReferences]
    public partial class SurgeryWindow : SS14Window
    {
        public SurgeryWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public IReadOnlyList<PartButton> PartButtons { get; set; } = new List<PartButton>();

        public void UpdateParts(IEnumerable<IBodyPart> parts)
        {
            Parts.DisposeAllChildren();

            var buttons = new List<PartButton>();

            foreach (var part in parts)
            {
                var button = new PartButton(part.Owner.Uid) {Text = Loc.GetString(part.Owner.Name)};

                Parts.AddChild(button);
                buttons.Add(button);
            }

            PartButtons = buttons;
        }
    }
}
